jobs:
  samples-build-VS-2019:
    runs-on: windows-2019

  strategy:
    matrix:
      configuration: [Release, Debug]
      platform: [x64]

  steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Build Emulator Core
      run: msbuild 'BitMagic.X16Emulator/X16Emulator/EmulatorCore/EmulatorCore.vcxproj' /p:configuration=${{ matrix.configuration }} /p:platform=${{ matrix.platform }}
