name: CI

on:
  push:
    branches: ["main"]
    workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        configuration: [Release, Debug]
        platform: [x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build Emulator Core
        run: msbuild 'BitMagic.X16Emulator/X16Emulator/EmulatorCore/EmulatorCore.vcxproj' /p:configuration=${{ matrix.configuration }} /p:platform=${{ matrix.platform }}

      - name: Build Debugger
        run: dotnet build 'BitMagic.X16Debugger/BitMagic.X16Debugger.sln' /p:configuration=${{ matrix.configuration }}

      - name: Build Emulator
        run: dotnet build 'BitMagic.X16Emulator/BitMagic.X16Emulator.sln' /p:configuration=${{ matrix.configuration }}        