name: Build

on:
  push:
    branches: ["main"]
    
jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build Emulator Core
        run: msbuild 'BitMagic.X16Emulator/X16Emulator/EmulatorCore/EmulatorCore.vcxproj' /p:configuration=Release /p:platform=x64

      - name: Build Debugger
        run: dotnet build 'BitMagic.X16Debugger/X16D/X16D.csproj' /p:configuration=Release --nologo

      - name: Make Debugger Folder
        run: mkdir BitMagic.X16Debugger\X16D\bin\Release\net6.0\EmulatorCore

      - name: Copy Core to Debugger
        run : copy-item 'BitMagic.X16Emulator\X16Emulator\EmulatorCore\x64\Release\EmulatorCore.dll' -Destination 'BitMagic.X16Debugger\X16D\bin\Release\net6.0\EmulatorCore\EmulatorCore.dll'

      - name: Build Emulator
        run: dotnet build 'BitMagic.X16Emulator/X16E/X16E.csproj' /p:configuration=Release --nologo

      - name: Make Emulator Folder
        run: mkdir BitMagic.X16Emulator\X16E\bin\Release\net6.0\EmulatorCore

      - name: Copy Core to Emulator
        run: copy-item 'BitMagic.X16Emulator\X16Emulator\EmulatorCore\x64\Release\EmulatorCore.dll' -Destination 'BitMagic.X16Emulator\X16E\bin\Release\net6.0\EmulatorCore\EmulatorCore.dll'

      - name: Create Version File
        run: |
          echo "${{ github.sha }}" > BitMagic.X16Emulator/X16E/bin/Release/net6.0/version.txt
          echo "${{ github.sha }}" > BitMagic.X16Debugger/X16D/bin/Release/net6.0/version.txt
          echo "${{ github.sha }}" > version.txt

      - name: Setup VS Dev
        uses: seanmiddleditch/gha-setup-vsdevenv@v4

      - name: Build MSI
        run: devenv.com BitMagic.X16Emulator\BitMagic.X16Emulator.sln /project BitMagic.X16Emulator\X16ESetup\X16ESetup.vdproj /build "Release|x64"

      # We dont need artifacts, but left this here just in case.
      # - name: Save Emulator Artifacts
      #   uses: actions/upload-artifact@v3
      #   with: 
      #     name: BitMagic-TheEmulator
      #     path: BitMagic.X16Emulator/X16E/bin/Release/net6.0/*

      # - name: Save Debugger Artifacts
      #   uses: actions/upload-artifact@v3
      #   with: 
      #     name: BitMagic-TheDebugger
      #     path: BitMagic.X16Debugger/X16D/bin/Release/net6.0/*
  
      - name: Archive Emulator
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'BitMagic-TheEmulator.zip'
          directory: BitMagic.X16Emulator/X16E/bin/Release/net6.0

      - name: Archive Debugger
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'BitMagic-TheDebugger.zip'
          directory: BitMagic.X16Debugger/X16D/bin/Release/net6.0    

      - name: Create Github Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "latest"
          title: "Development Build"
          files: |
            BitMagic.X16Emulator/X16E/bin/Release/net6.0/BitMagic-TheEmulator.zip
            BitMagic.X16Debugger/X16D/bin/Release/net6.0/BitMagic-TheDebugger.zip
            BitMagic.X16Emulator/X16ESetup/Release/X16Setup.msi
            version.txt