name: Build

on:
  push:
    branches: ["main"]
    workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build Emulator Core
        run: msbuild 'BitMagic.X16Emulator/X16Emulator/EmulatorCore/EmulatorCore.vcxproj' /p:configuration=Release /p:platform=x64

      - name: Build Debugger
        run: dotnet build 'BitMagic.X16Debugger/X16D/X16D.csproj' /p:configuration=Release --nologo

      - name: Copy Core to Debugger
        run : copy-item 'BitMagic.X16Emulator\X16Emulator\EmulatorCore\x64\Release\EmulatorCore.dll' -Destination 'BitMagic.X16Debugger\X16D\bin\Release\net6.0\EmulatoreCore\EmulatorCore.dll'

      - name: Save Debugger Artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: BitMagic-TheDebugger
          path: BitMagic.X16Debugger/X16D/bin/Release/net6.0/*

      - name: Build Emulator
        run: dotnet build 'BitMagic.X16Emulator/X16E/X16E.csproj' /p:configuration=Release --nologo

      - name: Copy Core to Emulator
        run: copy-item 'BitMagic.X16Emulator\X16Emulator\EmulatorCore\x64\Release\EmulatorCore.dll' -Destination 'BitMagic.X16Emulator\X16E\bin\Release\net6.0\EmulatoreCore\EmulatorCore.dll'

      - name: Save Emulator Artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: BitMagic-TheEmulator
          path: BitMagic.X16Emulator/X16E/bin/Release/net6.0/*
